-- CreateTable
CREATE TABLE "PembenahanWpNamaTtlSama" (
    "id" SERIAL NOT NULL,
    "npwp" TEXT,
    "nama" TEXT,
    "nik" TEXT,
    "alamat" TEXT,
    "nomorHp" TEXT,
    "email" TEXT,
    "tmpLahir" TEXT,
    "tglLahir" TEXT,
    "kpp" TEXT,
    "kanwil" TEXT,
    "nipId" TEXT,
    "seksi" TEXT,
    "status" TEXT,
    "noKep" INTEGER,
    "stsValid" TEXT,
    "thnLaporTerakhir" INTEGER,
    "jmlLapor10Thn" INTEGER,
    "tglBayarTerakhir" TEXT,
    "jmlBayar10thn" DOUBLE PRECISION,
    "thnPhTerakhir" INTEGER,
    "jmlPh10Thn" INTEGER,
    "saldoUtang" DOUBLE PRECISION,
    "tglUpdateTerakhir" TEXT,
    "npwpSama" TEXT,
    "namaSama" TEXT,
    "nikSama" TEXT,
    "alamatSama" TEXT,
    "nomorHpSama" TEXT,
    "emailSama" TEXT,
    "tmpLahirSama" TEXT,
    "tglLahirSama" TEXT,
    "kppSama" TEXT,
    "kanwilSama" TEXT,
    "arSama" TEXT,
    "seksiSama" TEXT,
    "statusSama" TEXT,
    "noKepSama" TEXT,
    "stsValidSama" TEXT,
    "thnLaporTerakhirSama" INTEGER,
    "jmlLapor10ThnSama" INTEGER,
    "tglBayarTerakhirSama" TEXT,
    "jmlBayar10ThnSama" DOUBLE PRECISION,
    "thnPhTerakhirSama" INTEGER,
    "jmlPh10ThnSama" INTEGER,
    "saldoUtangSama" DOUBLE PRECISION,
    "tglUpdateTerakhirSama" TEXT,
    "skorJwsNama" INTEGER,
    "skorJwsTempat" INTEGER,
    "skorEdsNama" INTEGER,
    "skorEdsTempat" INTEGER,
    "tglBentukData" TEXT,

    CONSTRAINT "PembenahanWpNamaTtlSama_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "PembenahanWpNamaTtlSama" ADD CONSTRAINT "PembenahanWpNamaTtlSama_nipId_fkey" FOREIGN KEY ("nipId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
