-- AlterTable
ALTER TABLE "BedahWPDummy" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "kunci" BOOLEAN DEFAULT false,
ADD COLUMN     "pajakLainnya" DOUBLE PRECISION,
ADD COLUMN     "pelaksanaanKegiatan" TIMESTAMP(3),
ADD COLUMN     "pph15" DOUBLE PRECISION,
ADD COLUMN     "pph21" DOUBLE PRECISION,
ADD COLUMN     "pph22" DOUBLE PRECISION,
ADD COLUMN     "pph23" DOUBLE PRECISION,
ADD COLUMN     "pph2529" DOUBLE PRECISION,
ADD COLUMN     "pph26" DOUBLE PRECISION,
ADD COLUMN     "pphFinal" DOUBLE PRECISION,
ADD COLUMN     "ppn" DOUBLE PRECISION,
ADD COLUMN     "sendingDataToKanwilId" INTEGER,
ADD COLUMN     "userId" TEXT;

-- AddForeignKey
ALTER TABLE "BedahWPDummy" ADD CONSTRAINT "BedahWPDummy_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BedahWPDummy" ADD CONSTRAINT "BedahWPDummy_sendingDataToKanwilId_fkey" FOREIGN KEY ("sendingDataToKanwilId") REFERENCES "SendingDataToKanwil"("id") ON DELETE SET NULL ON UPDATE CASCADE;
