-- CreateTable
CREATE TABLE "PembenahanWpNikGanda" (
    "id" SERIAL NOT NULL,
    "no" INTEGER,
    "npwp1" TEXT,
    "nama1" TEXT,
    "nik1" TEXT,
    "kpp1" TEXT,
    "kanwil1" TEXT,
    "statusValid1" TEXT,
    "statusWp1" TEXT,
    "updatedBy1" TEXT,
    "noKep1" TEXT,
    "penerimanFasilitasPen1" TEXT,
    "dataLapor1" INTEGER,
    "dataBayar1" INTEGER,
    "dataTunggakan1" INTEGER,
    "jumlahData1" TEXT,
    "dataTransaksi1" TEXT,
    "tempatLahir1" TEXT,
    "tanggalLahir1" TEXT,
    "npwp2" TEXT,
    "nama2" TEXT,
    "nik2" TEXT,
    "kpp2" TEXT,
    "kanwil2" TEXT,
    "statusValid2" TEXT,
    "statusWp2" TEXT,
    "updateBy2" TEXT,
    "noKep2" TEXT,
    "penerimaFasilitasPen2" TEXT,
    "dataLapor2" INTEGER,
    "dataBayar2" INTEGER,
    "dataTunggakan2" INTEGER,
    "jumlahData2" INTEGER,
    "dataTransaksi2" TEXT,
    "tempatLahir2" TEXT,
    "tanggalLahir2" TEXT,
    "kppTerdaftar1dan2" TEXT,
    "hasilCekNikDukcapil" TEXT,
    "namaDukcapil" TEXT,
    "persenNamaDukcapil" INTEGER,
    "edsSkor" INTEGER,
    "jswSkor" INTEGER,
    "cosSkor" INTEGER,
    "diceSkor" INTEGER,

    CONSTRAINT "PembenahanWpNikGanda_pkey" PRIMARY KEY ("id")
);
